# Generated by Django 3.1.1 on 2020-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='сooking_time',
            field=models.TimeField(null=True),
        ),
    ]
