# Generated by Django 3.1.1 on 2020-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_сooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='сooking_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
